# Generated by Django 3.2.3 on 2021-07-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Typing_practise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True)),
                ('typing_speed', models.IntegerField()),
                ('accuracy', models.IntegerField()),
            ],
        ),
    ]
