# Generated by Django 3.2.5 on 2021-07-17 08:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('typing_practise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typing_practise',
            name='post_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
